### ISSUE TITLE
Can't receive sms on my server

### ISSUE THREAD

**Issue by MikeDevresse** [styryl/goip#1]
Hi,

I don't know how to configure my Goip to receive sms. Can you help me with this ? It's really important.
You can contact me on discord : Mike#7697

Thank you

**Comment by styryl** [comment]
I will update the manual in the next few days.
Enter the goip administration panel (for goip1):

Configurations-> sms

SMS Server: enable
SMS Server IP: your server address
SMS Server Port: the port of your server
SMS Client ID: goip id (string)
Password: password (string)

Press save changes

E.g:

```php
use Pikart\Goip\ServerFactory;
use Pikart\Goip\ReactServer;
use Pikart\Goip\Message;
use Pikart\Goip\Messages\ReceiveMessage;

$server = ServerFactory::default( ReactServer::class, '192.168.0.10', 3000);

$server->listenAll(function (Message $message){
    // Array of all attributes
    $attributes = $message->attributes();

    // Pikart\Goip\Request::class Access to raw request from goip
    $request = $message->request();

    // Show remote host and port
    $remoteHost = $message->request()->host();
    $remotePort = $message->request()->port();

});
```

SMS Server: enable
SMS Server IP: 192.168.0.10
SMS Server Port: 3000
SMS Client ID: my_goip_line_id
Password: my_goip_strong_password

**Comment by MikeDevresse** [comment]
Can you add me on discord so we can talk ? I have few more questions
